Gosa plugin pwreset v2.8
gosa-project/gosa-plugin-pwreset pull request #1
Opened 2021-11-17 15:08 UTC by Juinness

Plugin update for v2.8

2021-12-03 22:30 UTC, sunweaver requested changes
@Juinness Thanks for adjusting the pwreset plugin to GOsa 2.8. Thanks for working on this huge design lift up, as well. I assume that you have tested the code changes in this PR well, so code wise, the changes look ok to me (without smoke testing the changes).

However, the commit messages are rather dirty and don't provide enough documentation of this changeset. Also, I'd say, please squash all commits into one and provide a proper commit message for that (with a bit more information than is available now in the commit messages).

Thanks,
Mike

2021-12-06 07:33 UTC, Juinness commented
Hallo leider habe ich dort beim abarbeiten der Pull Request nicht ganz aufgepasst. Die Änderungen beziehen sich alle auf den Frontend bereich. Ich werde die Commits anpassen und die Pull Requests abändern. Das auch die Beschreibung den Inhalt besser wiedergeben.

2025-11-26 16:43 UTC, dzatoah commented
ping

2026-01-28 16:22 UTC, sunweaver commented
Changes have been applied to main branch already and I have now configure the main branch as default branch. Thus, dropping the master branch any time soon. So this PR can be closed.

2026-01-28 16:22 UTC, closed without merging